In [3]:
print("Hello World!")

Hello World!

In [1]:
import pandas as pd
lst = ['Greeks', 'For', 'Greeks', 'is', 'portal', 'for', 'Geeks']

df = pd.DataFrame(lst)
print(df)

        0
0  Greeks
1     For
2  Greeks
3      is
4  portal
5     for
6   Geeks

In [4]:
df.drop_duplicates()

        0
0  Greeks
1     For
3      is
4  portal
5     for
6   Geeks

In [6]:
df.fillna(0)
df.dropna()

        0
0  Greeks
1     For
2  Greeks
3      is
4  portal
5     for
6   Geeks